Agrego de tipos a operaciones
DDLuna/unlam_compiler pull request #3
Opened 2019-10-09 23:32 UTC by SebastianBarros

Para saber si una asignación/operación(comparación debe realizarse capando decimales o teniéndolos en cuenta, se le agrega en los nodos de cada uno el tipo que debe resultar.
Es decir, si un = dice int al lado (se puede ver en el gráfico del árbol, no en la intermedia), sabés que al momento de asignar, no debés tener en cuenta decimales. Así con todo.

2019-10-10 00:00 UTC, DDLuna commented on sintactico.y
> +		$$ = crear_nodo("PRINT","string",NULL,crear_hoja($2,NULL));
Usar strings literales hace que después sea más dificil hacer cambios. Cambiar las ocurrencias por variables constantes:
ej:
const char* STRING = "string";

2019-10-10 00:02 UTC, DDLuna commented on sintactico.y
> +	return id->tipo;
Puede darse le caso que id sea null? Si es así explota, tal vez para como lo usamos no sucede nunca, pero por buena práctica agregaría un if (id) {...}
Tal vez nos salve de tener que debuggear luego.

2019-10-10 00:03 UTC, DDLuna requested changes
Cambiar los literales string por variables constantes y revisar por null en funcion que obtiene el tipo de árbol.

2019-10-10 00:43 UTC, DDLuna commented on sintactico.y
> +#define CONSTSTRING "constString"
Si bien para nuestro caso va a funcionar, estos defines no están buenos para representar constantes, cambiar a
const char* VARIABLE = "variable";

2019-10-10 00:45 UTC, DDLuna commented on sintactico.y
> +	if(!*id){
Aca estás desreferenciando el puntero id... si id apunta a null esto explota, lo que tenés que chequear acá es si id apunta a null:
if (id) {

}

2019-10-10 01:59 UTC, DDLuna commented on sintactico.y
> +		strcpy(tipo_dato, CONSTFLOAT);
tipo_dato puede pasarte a puntero const y evitar usar strcpy

2019-10-10 02:01 UTC, DDLuna requested changes
Cambiar tipo dato y valor const a punteros const y sacar strcpy

2019-10-10 15:43 UTC, GCoradini requested changes

2019-10-10 15:43 UTC, GCoradini commented on sintactico.y
> +	if(strcmp(tipo, CONSTFLOAT) == 0){ //si es un const string
Comparas contra un CONSTFLOAT para sacar la longitud de una constante string.
No deberia ser CONSTSTRING?

2019-10-10 16:15 UTC, GCoradini approved these changes

2019-10-11 07:05 UTC, DDLuna approved these changes

2019-10-11 07:05 UTC, merged